import Head from "next/head";
import type { NextPage } from "next";

import styles from "../styles/Home.module.scss";
import Hero from "components/Hero";
import Tagline from "components/Tagline";
import OurWorks from "components/OurWorks";
import Partners from "components/Partners";

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Tagline />
        <OurWorks />
        <Partners />
      </main>
    </div>
  );
};

export default Home;
